language: go
go:
  - 1.2
  - 1.3
  - tip
install:
  - go get github.com/tools/godep
script:
  - godep go test
notifications:
  email:
    recipients:
      - simon.raphael@gmail.com
    on_success: change
    on_failure: always

